on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:
    branches:
      - master

jobs:
  test_and_build:
    name: Test & Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
      fail-fast: false
    env:
      RUST_BACKTRACE: 1

    steps:
      - name: âœ… Checkout
        uses: actions/checkout@v2
      - name: âš™ï¸ Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: ğŸ§ Dependencies
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y libudev-dev
      - name: ğŸ Dependencies
        if: matrix.os == 'macos-latest'
        run: brew install automake
      - name: âš¡ Cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ matrix.os }}-${{ hashFiles('**/Cargo.toml') }}
      - name: ğŸ” Test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: ğŸ”¨ Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

  publish:
    name: Publish
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: windows-latest
    needs: test_and_build
    steps:
      - name: âœ… Checkout
        uses: actions/checkout@v2
      - name: âš™ï¸ Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: âš¡ Cache
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: windows-latest-${{ hashFiles('**/Cargo.toml') }}
      - name: âš¡ Cache Bin
        uses: actions/cache@v2.1.4
        with:
          path: |
            ~/.cargo/bin/cargo-release
          key: cargo-bin
      - name: ğŸš€ Publish
        run: |
          cargo login ${{ secrets.CRATES_IO_TOKEN }}
          cargo install cargo-release
          cargo release --no-confirm --no-dev-version --skip-tag --skip-push
